framework:
    mailer:
        dsn: 'gmail+smtp://default?oauth&user=ecocollectes@gmail.com&clientId=84655846672-81hnpk3qok8sd5bio1bb7eftp0nc82a5.apps.googleusercontent.com&clientSecret=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&accessToken=yourAccessToken&refreshToken=yourRefreshToken'
